apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: vn30
    secureJsonData:
      password: vn30_dev_only
    jsonData:
      database: vn30_pipeline
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
